export const copy = {
  meta: {
    title: "SaaS Generator — From Idea to Launch in Minutes",
    description:
      "AI researches your niche, generates the SaaS, builds the code, and deploys it. You just pick the winners.",
  },

  hero: {
    headline: "From idea to launch in minutes, not months.",
    subhead:
      "AI researches your niche, generates the SaaS, builds the code, and deploys it. You just pick the winners.",
    ctaPrimary: "Start Generating — Free",
    ctaSecondary: "See How It Works",
    pipelineSteps: ["Research", "Generate", "Build", "Launch"],
    liveIndicator: "12 makers building right now",
  },

  nav: {
    cta: "Get started",
  },

  socialProof: {
    heading: "Trusted by indie makers shipping real products",
    stats: [
      { value: "2,400+", label: "SaaS apps generated" },
      { value: "840+", label: "Active makers" },
      { value: "$1.2M", label: "Revenue generated by user products" },
      { value: "4.9/5", label: "Average rating" },
    ],
  },

  howItWorks: {
    heading: "How it works",
    subheading: "Three steps from idea to live product.",
    steps: [
      {
        number: "01",
        title: "Pick a niche or let AI find one",
        description:
          "AI scans Reddit, HN, Product Hunt, Google Trends — identifies pain points and underserved markets. Scores niches by demand, competition, and monetization potential.",
      },
      {
        number: "02",
        title: "Generate your SaaS",
        description:
          "AI creates 5–10 ideas per niche with full specs. Domain availability check, competitor analysis included. Pick your favorite and customize the MVP scope.",
      },
      {
        number: "03",
        title: "Ship it",
        description:
          "AI generates a production-ready Next.js app. Landing page, auth, Stripe billing, core feature. Deploys to Vercel with your custom domain. You're live.",
      },
    ],
  },

  testimonials: [
    {
      quote:
        "I had a landing page idea at 11pm. By midnight I had a deployed SaaS with Stripe billing. This is genuinely bonkers.",
      author: "Marcus T.",
      role: "Indie Hacker, 3 apps this month",
      avatar: "M",
    },
    {
      quote:
        "I've tried every AI code tool. This is the only one that actually ships a production-ready app. My Stripe account got its first payment in 40 minutes.",
      author: "Priya S.",
      role: "Founder, InvoicePilot",
      avatar: "P",
    },
    {
      quote:
        "Wanted to test a niche before committing. Generated 8 ideas, picked the best, had a live product in 2 hours. No code. No credit card needed to start.",
      author: "Jake W.",
      role: "Product tester, $0 spent",
      avatar: "J",
    },
  ],

  liveExamples: {
    heading: "Live examples",
    subheading: "These were generated and deployed with SaaS Generator.",
    examples: [
      {
        name: "InvoicePilot",
        tagline: "AI invoices for freelancers",
        description:
          "Generate polished, professional invoices in seconds. AI learns your style, auto-fills line items, and sends reminders so you never chase a payment again.",
        liveUrl: "#",
        sourceUrl: "#",
      },
      {
        name: "ReviewSnap",
        tagline: "Auto-respond to customer reviews",
        description:
          "Monitor all your reviews in one place. AI crafts thoughtful, brand-voice responses in seconds so you stay present without losing hours to manual replies.",
        liveUrl: "#",
        sourceUrl: "#",
      },
      {
        name: "WaitlistHero",
        tagline: "Launch waitlists in 60 seconds",
        description:
          "Stop losing early adopters while you build. Create a waitlist page, collect emails, and generate buzz before you've written a single line of product code.",
        liveUrl: "#",
        sourceUrl: "#",
      },
    ],
  },

  whatGetsGenerated: {
    heading: "What you get",
    subheading: "A fully-baked SaaS, ready for your first customers.",
    features: [
      {
        icon: "Layout",
        title: "Responsive landing page",
        description: "SEO-optimized with Open Graph, sitemap, and schema markup.",
      },
      {
        icon: "LogIn",
        title: "Authentication",
        description: "Google OAuth and email/password with secure session management.",
      },
      {
        icon: "CreditCard",
        title: "Stripe billing",
        description: "Free and paid tiers, checkout flows, webhook handling, and invoices.",
      },
      {
        icon: "Database",
        title: "Database",
        description: "Prisma ORM with PostgreSQL. Schema, migrations, and seed data.",
      },
      {
        icon: "BarChart3",
        title: "Admin dashboard",
        description: "User management, revenue metrics, and usage analytics out of the box.",
      },
      {
        icon: "Zap",
        title: "API endpoints",
        description: "RESTful routes with auth guards, rate limiting, and error handling.",
      },
      {
        icon: "Mail",
        title: "Email notifications",
        description: "Transactional email via Resend. Welcome, billing, and alert templates.",
      },
      {
        icon: "PieChart",
        title: "Analytics setup",
        description: "Vercel Analytics, PostHog events, and a pre-built dashboard.",
      },
    ],
  },

  techStack: {
    heading: "Built on the stack you already trust",
    logos: ["Next.js", "Stripe", "Vercel", "Supabase", "Tailwind CSS", "TypeScript"],
  },

  pricing: {
    heading: "Simple pricing",
    subheading: "Start free. Scale when you're ready.",
    urgencyNote: "Beta pricing — 40% off for early adopters. Ends when we launch publicly.",
    tiers: [
      {
        name: "Hobby",
        price: "0",
        period: "mo",
        description: "For trying things out and testing ideas.",
        features: [
          "1 project",
          "Community support",
          "Basic niche research",
          "Subdomain deployment",
        ],
        cta: "Start for free",
        featured: false,
      },
      {
        name: "Maker",
        price: "29",
        period: "mo",
        description: "For indie hackers shipping real products.",
        features: [
          "5 projects",
          "Custom domains",
          "Priority support",
          "Competitor analysis",
          "Stripe billing",
          "Remove watermarks",
        ],
        cta: "Start building",
        featured: true,
      },
      {
        name: "Studio",
        price: "99",
        period: "mo",
        description: "For teams and serious product velocity.",
        features: [
          "Unlimited projects",
          "White-label code",
          "API access",
          "Team members",
          "Custom integrations",
          "Dedicated support",
        ],
        cta: "Contact us",
        featured: false,
      },
    ],
  },

  faq: {
    heading: "FAQ",
    questions: [
      {
        q: "What kind of apps can it generate?",
        a: "SaaS Generator works best for micro-SaaS products: billing tools, productivity apps, community platforms, and data dashboards. It generates a complete Next.js app with auth, payments, and a core feature scaffold — so anything that fits that mold is a great fit.",
      },
      {
        q: "Do I need to know how to code?",
        a: "No. You direct the AI with natural language. Pick your niche, review the generated ideas, select the one you like, and the AI builds it. You can read and edit the code if you want — it's yours.",
      },
      {
        q: "Who owns the code?",
        a: "You do. Every generated app is MIT licensed. You get a full GitHub repository with production-ready code. Deploy anywhere — Vercel, Railway, Fly.io, your own server.",
      },
      {
        q: "What does it cost to run the generated app?",
        a: "Your main costs are: Vercel (free tier covers most micro-SaaS), Supabase (free tier has 500MB database), Stripe (2.9% + 30¢ per transaction). A micro-SaaS with 100 users costs ~$0-20/month to run.",
      },
      {
        q: "How long does it take?",
        a: "Research + idea generation: 2–5 minutes. Code generation + build: 3–8 minutes. Total: under 15 minutes from niche to live URL.",
      },
      {
        q: "Is there a waitlist?",
        a: "No waitlist — join now and start building immediately. Beta users get 40% off Maker plan for life.",
      },
    ],
  },

  finalCta: {
    heading: "Your SaaS is closer than you think.",
    subheadline:
      "Stop planning. Start shipping. Pick a niche, let AI do the rest.",
    cta: "Start generating — free",
  },
};
