/**
 * Orchestrator Engine — manages the full generate → build → launch pipeline
 */

import { execSync } from "child_process";
import {
  createRepo,
  createIssue,
  createWorktree,
  gh,
  type RepoInfo,
} from "./github";
import {
  createProject,
  transitionStatus,
  updateProject,
  addEvent,
  type SaaSProject,
} from "./projects";
import { dbConnect, dbUpdateProject, dbCreateProject } from "./db";
import type { GeneratedIdea, ResearchResult } from "./projects";
import { searchReddit, searchTrends, synthesizeResearch } from "./research";
import { generateIdeasFromResearch } from "./ideas";
import { spawnCodeGenerationAgents } from "./code-generator";
import { fullDeploy } from "./vercel";
import { sendBuildStartedEmail, sendDeployCompleteEmail } from "./email";

// ─── Types ───────────────────────────────────────────────

export interface GenerateOptions {
  projectName: string;
  niche?: string;
  description?: string;
  isPublic?: boolean;
}

export interface GenerateResult {
  project: SaaSProject;
  repo: RepoInfo;
  issues: Array<{ number: number; title: string; url: string }>;
}

// ─── Pipeline Steps ─────────────────────────────────────

export async function initializeProject(
  opts: GenerateOptions & { userId?: string }
): Promise<GenerateResult> {
  const project = createProject(opts.projectName);

  // Persist to DB (non-blocking — errors are logged but don't break the flow)
  dbCreateProject({ name: opts.projectName, userId: opts.userId }).catch(
    (err) => console.error("[DB] Failed to create project in DB:", err)
  );

  transitionStatus(project.id, "building", "Creating GitHub repository...", "info");

  let repo: RepoInfo;
  try {
    repo = createRepo({
      name: opts.projectName.toLowerCase().replace(/\s+/g, "-"),
      description: opts.description ?? "Generated by SaaS Generator Tool",
      public: opts.isPublic ?? true,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (msg.includes("already exists") || msg.includes("Already exists")) {
      const repoName = opts.projectName.toLowerCase().replace(/\s+/g, "-");
      const url = gh(`repo view ${repoName} --json url,sshUrl,name,owner -q '.'`);
      const data = JSON.parse(url) as {
        url: string; sshUrl: string; name: string; owner: { login: string };
      };
      repo = { url: data.url, sshUrl: data.sshUrl, name: data.name, owner: data.owner.login };
    } else {
      addEvent(project.id, `GitHub repo creation failed: ${msg}`, "error");
      throw err;
    }
  }

  addEvent(project.id, `GitHub repo created: ${repo.url}`, "success");
  updateProject(project.id, { githubRepo: repo.url, name: opts.projectName });

  const issueTitles = [
    "🏗️ Project scaffolding — Next.js + Tailwind + auth",
    "🎨 Landing page — hero, features, pricing, FAQ",
    "💳 Stripe billing — subscriptions + checkout",
    "🔐 Auth flow — signup, login, password reset",
    "📊 Admin dashboard — user management + analytics",
    "🚀 Deployment — Vercel + custom domain + monitoring",
  ];

  const issues = issueTitles.map((title, i) =>
    createIssue(`${repo.owner}/${repo.name}`, {
      title,
      body: `This issue was auto-generated by the SaaS Generator Tool.\n\nPriority: ${i < 2 ? "high" : "medium"}\nStatus: open`,
      labels: ["backend", i === 1 ? "frontend" : "backend"],
    })
  );

  addEvent(project.id, `${issues.length} GitHub issues created`, "success");
  transitionStatus(project.id, "building", "Ready for development", "info");

  return {
    project: updateProject(project.id, {})!,
    repo,
    issues: issues.map((i, idx) => ({
      number: i.number,
      title: issueTitles[idx].replace(/[^a-zA-Z0-9 ]/g, "").trim(),
      url: i.url,
    })),
  };
}

export async function researchAndGenerateIdeas(
  projectId: string,
  niche?: string
): Promise<{ research: ResearchResult; ideas: GeneratedIdea[] }> {
  transitionStatus(projectId, "researching", "Researching market trends...", "info");

  const targetNiche =
    niche ?? "AI-powered productivity tools for freelancers";

  const [redditPosts, trends] = await Promise.all([
    searchReddit(targetNiche),
    searchTrends(targetNiche),
  ]);

  const research = await synthesizeResearch(targetNiche, redditPosts, trends);

  addEvent(projectId, `Research complete for "${targetNiche}"`, "success");
  transitionStatus(
    projectId,
    "generating_ideas",
    "Generating SaaS ideas from research...",
    "info"
  );

  const ideas = generateIdeasFromResearch(
    targetNiche,
    research.demandScore,
    research.competitionScore,
    research.painPoints,
    research.suggestedFeatures,
    research.pricingSuggestion
  );

  addEvent(projectId, `${ideas.length} ideas generated`, "success");
  transitionStatus(
    projectId,
    "selecting",
    "Ideas ready — awaiting user selection",
    "info"
  );

  updateProject(projectId, { researchData: research, ideas });
  return { research, ideas };
}

export async function selectIdeaAndBuild(
  projectId: string,
  ideaIndex: number
): Promise<{ worktrees: string[]; prs: string[] }> {
  const project = updateProject(projectId, {})!;
  const selectedIdea = project.ideas?.[ideaIndex];
  if (!selectedIdea) {
    throw new Error(`Invalid idea index: ${ideaIndex}`);
  }

  updateProject(projectId, { selectedIdea });
  transitionStatus(
    projectId,
    "building",
    `Selected idea: ${selectedIdea.name} — spawning agents...`,
    "info"
  );

  if (!project.githubRepo) {
    throw new Error("No GitHub repo configured for this project");
  }

  const repoSlug = project.githubRepo
    .replace("https://github.com/", "")
    .replace(/\.git$/, "");

  const repoDir = `/tmp/saas-gen-${project.id}`;
  try {
    execSync(`git clone https://github.com/${repoSlug}.git ${repoDir}`, {
      stdio: "pipe",
    });
  } catch {
    // Already cloned
  }

  const branches = [
    { name: "feat/scaffolding", task: "Project setup" },
    { name: "feat/landing-page", task: `Landing page for ${selectedIdea.name}` },
    { name: "feat/stripe-billing", task: "Stripe billing" },
    { name: "feat/core-feature", task: `Core feature: ${selectedIdea.coreFeature}` },
  ];

  for (const branch of branches) {
    addEvent(projectId, `Creating branch: ${branch.name}`, "info");
    createWorktree(repoDir, branch.name);
  }

  const codeGenResult = await spawnCodeGenerationAgents(project, repoDir);

  transitionStatus(
    projectId,
    "building",
    `${codeGenResult.branches.length} agents spawned`,
    "info"
  );

  // Send build-started email (async, non-blocking — will be real email after auth is wired)
  const baseUrl = process.env.NEXTAUTH_URL ?? "http://localhost:3457";
  sendBuildStartedEmail({
    to: "user@example.com", // TODO: replace with authenticated user email
    projectName: selectedIdea.name,
    ideaName: selectedIdea.name,
    dashboardUrl: `${baseUrl}/dashboard/${projectId}`,
  }).catch((err) => console.error("[Email] build-started failed:", err));

  return {
    worktrees: codeGenResult.branches.map((b) => b.worktreePath),
    prs: codeGenResult.branches.map((b) => b.prUrl),
  };
}

export async function deployProject(projectId: string): Promise<{ url: string }> {
  transitionStatus(projectId, "deploying", "Connecting to Vercel...", "info");

  const project = updateProject(projectId, {})!;
  const { url: deployedUrl } = await fullDeploy({
    name: project.name,
    githubRepo: project.githubRepo ?? "",
    envVars: {
      EXA_API_KEY: process.env.EXA_API_KEY ?? "",
      STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY ?? "",
    },
    token: process.env.VERCEL_API_TOKEN,
  });

  addEvent(projectId, `Deployed to Vercel: ${deployedUrl}`, "success");
  try { await dbConnect(); await dbUpdateProject(projectId, { vercelUrl: deployedUrl, status: "live" }); } catch {}
  updateProject(projectId, { vercelUrl: deployedUrl });
  transitionStatus(projectId, "live", "🚀 Project is live!", "success");

  // Send deploy-complete email
  const baseUrl = process.env.NEXTAUTH_URL ?? "http://localhost:3457";
  sendDeployCompleteEmail({
    to: "user@example.com", // TODO: replace with authenticated user email
    projectName: project.name,
    ideaName: project.selectedIdea?.name ?? project.name,
    vercelUrl: deployedUrl,
    githubUrl: project.githubRepo ?? "",
    dashboardUrl: `${baseUrl}/dashboard/${projectId}`,
  }).catch((err) => console.error("[Email] deploy-complete failed:", err));

  return { url: deployedUrl };
}
