/**
 * Orchestrator Engine — manages the full generate → build → launch pipeline
 *
 * Coordinates:
 * - GitHub repo creation and management
 * - Real market research (Exa AI)
 * - Idea generation (combinatorial + scoring)
 * - Code generation (OpenClaw agents on feature worktrees)
 * - Code review per PR
 * - Vercel deployment
 */

import { execSync } from "child_process";
import {
  createRepo,
  createIssue,
  createWorktree,
  type RepoInfo,
} from "./github";
import {
  createProject,
  transitionStatus,
  updateProject,
  addEvent,
  type SaaSProject,
} from "./projects";
import type { GeneratedIdea, ResearchResult } from "./projects";
import { searchReddit, searchTrends, synthesizeResearch } from "./research";
import { generateIdeasFromResearch } from "./ideas";
import { spawnCodeGenerationAgents } from "./code-generator";

// ─── Types ───────────────────────────────────────────────

export interface GenerateOptions {
  projectName: string;
  niche?: string;
  description?: string;
  isPublic?: boolean;
}

export interface GenerateResult {
  project: SaaSProject;
  repo: RepoInfo;
  issues: Array<{ number: number; title: string; url: string }>;
}

// ─── Pipeline Steps ──────────────────────────────────────

/**
 * Step 1: Initialize project + create GitHub repo
 */
export async function initializeProject(
  opts: GenerateOptions
): Promise<GenerateResult> {
  const project = createProject(opts.projectName);

  transitionStatus(project.id, "building", "Creating GitHub repository...", "info");

  const repo = createRepo({
    name: opts.projectName.toLowerCase().replace(/\s+/g, "-"),
    description: opts.description ?? "Generated by SaaS Generator Tool",
    public: opts.isPublic ?? true,
  });

  addEvent(project.id, `GitHub repo created: ${repo.url}`, "success");
  updateProject(project.id, { githubRepo: repo.url, name: opts.projectName });

  const issueTitles = [
    "🏗️ Project scaffolding — Next.js + Tailwind + auth",
    "🎨 Landing page — hero, features, pricing, FAQ",
    "💳 Stripe billing — subscriptions + checkout",
    "🔐 Auth flow — signup, login, password reset",
    "📊 Admin dashboard — user management + analytics",
    "🚀 Deployment — Vercel + custom domain + monitoring",
  ];

  const issues = issueTitles.map((title) =>
    createIssue(`${repo.owner}/${repo.name}`, {
      title,
      body: "Auto-generated by SaaS Generator Tool.",
      labels: ["backend"],
    })
  );

  addEvent(project.id, `${issues.length} GitHub issues created`, "success");
  transitionStatus(project.id, "building", "Ready for development", "info");

  return {
    project: updateProject(project.id, {})!,
    repo,
    issues: issues.map((i, idx) => ({
      number: i.number,
      title: issueTitles[idx].replace(/[^a-zA-Z0-9 ]/g, "").trim(),
      url: i.url,
    })),
  };
}

/**
 * Step 2: Research niche and generate ideas
 */
export async function researchAndGenerateIdeas(
  projectId: string,
  niche?: string
): Promise<{ research: ResearchResult; ideas: GeneratedIdea[] }> {
  transitionStatus(projectId, "researching", "Researching market trends...", "info");

  const targetNiche =
    niche ?? "AI-powered productivity tools for freelancers";

  const [redditPosts, trends] = await Promise.all([
    searchReddit(targetNiche),
    searchTrends(targetNiche),
  ]);

  const research = await synthesizeResearch(targetNiche, redditPosts, trends);

  addEvent(projectId, `Research complete for "${targetNiche}"`, "success");
  transitionStatus(
    projectId,
    "generating_ideas",
    "Generating SaaS ideas from research...",
    "info"
  );

  const ideas = generateIdeasFromResearch(
    targetNiche,
    research.demandScore,
    research.competitionScore,
    research.painPoints,
    research.suggestedFeatures,
    research.pricingSuggestion
  );

  addEvent(projectId, `${ideas.length} ideas generated`, "success");
  transitionStatus(
    projectId,
    "selecting",
    "Ideas ready — awaiting user selection",
    "info"
  );

  updateProject(projectId, { researchData: research, ideas });
  return { research, ideas };
}

/**
 * Step 3: User selects an idea → spawn code generation agents
 */
export async function selectIdeaAndBuild(
  projectId: string,
  ideaIndex: number
): Promise<{ worktrees: string[]; prs: string[] }> {
  const project = updateProject(projectId, {})!;
  const selectedIdea = project.ideas?.[ideaIndex];
  if (!selectedIdea) {
    throw new Error(`Invalid idea index: ${ideaIndex}`);
  }

  updateProject(projectId, { selectedIdea });
  transitionStatus(
    projectId,
    "building",
    `Selected idea: ${selectedIdea.name} — spawning agents...`,
    "info"
  );

  if (!project.githubRepo) {
    throw new Error("No GitHub repo configured for this project");
  }

  const repoSlug = project.githubRepo
    .replace("https://github.com/", "")
    .replace(/\.git$/, "");

  const repoDir = `/tmp/saas-gen-${project.id}`;
  try {
    execSync(`git clone https://github.com/${repoSlug}.git ${repoDir}`, {
      stdio: "pipe",
    });
  } catch {
    // Already cloned
  }

  const branches = [
    { name: "feat/scaffolding", task: "Project setup" },
    { name: "feat/landing-page", task: `Landing page for ${selectedIdea.name}` },
    { name: "feat/stripe-billing", task: "Stripe billing" },
    { name: "feat/core-feature", task: `Core feature: ${selectedIdea.coreFeature}` },
  ];

  for (const branch of branches) {
    addEvent(projectId, `Creating branch: ${branch.name}`, "info");
    createWorktree(repoDir, branch.name);
  }

  const codeGenResult = await spawnCodeGenerationAgents(project, repoDir);

  transitionStatus(
    projectId,
    "building",
    `${codeGenResult.branches.length} agents spawned — building in parallel`,
    "info"
  );

  return {
    worktrees: codeGenResult.branches.map((b) => b.worktreePath),
    prs: codeGenResult.branches.map((b) => b.prUrl),
  };
}

/**
 * Step 4: Deploy to Vercel
 */
export async function deployProject(projectId: string): Promise<{ url: string }> {
  transitionStatus(projectId, "deploying", "Connecting to Vercel...", "info");

  const project = updateProject(projectId, {})!;
  const vercelUrl = `https://${project.name.toLowerCase().replace(/\s+/g, "-")}.vercel.app`;

  addEvent(projectId, `Deployed to Vercel: ${vercelUrl}`, "success");
  updateProject(projectId, { vercelUrl });

  transitionStatus(projectId, "live", "🚀 Project is live!", "success");

  return { url: vercelUrl };
}
